# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1081, 751)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.left_Widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_Widget.sizePolicy().hasHeightForWidth())
        self.left_Widget.setSizePolicy(sizePolicy)
        self.left_Widget.setObjectName("left_Widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_Widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.left_Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setToolTip("")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "Die_erste_Spalte")
        self.treeWidget.headerItem().setToolTip(0, "\"ersteSpalte\"")
        self.verticalLayout.addWidget(self.treeWidget)
        self.tabWidget = QtWidgets.QTabWidget(self.left_Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        self.tabWidget.setToolTip("")
        self.tabWidget.setAccessibleName("")
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.tab_1)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_legend = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_legend.sizePolicy().hasHeightForWidth())
        self.lineEdit_legend.setSizePolicy(sizePolicy)
        self.lineEdit_legend.setObjectName("lineEdit_legend")
        self.gridLayout_3.addWidget(self.lineEdit_legend, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.lineEdit_units = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_units.sizePolicy().hasHeightForWidth())
        self.lineEdit_units.setSizePolicy(sizePolicy)
        self.lineEdit_units.setObjectName("lineEdit_units")
        self.gridLayout_3.addWidget(self.lineEdit_units, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_id = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_id.sizePolicy().hasHeightForWidth())
        self.lineEdit_id.setSizePolicy(sizePolicy)
        self.lineEdit_id.setObjectName("lineEdit_id")
        self.gridLayout_3.addWidget(self.lineEdit_id, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 2, 1, 1)
        self.lineEdit_connection = QtWidgets.QLineEdit(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_connection.sizePolicy().hasHeightForWidth())
        self.lineEdit_connection.setSizePolicy(sizePolicy)
        self.lineEdit_connection.setObjectName("lineEdit_connection")
        self.gridLayout_3.addWidget(self.lineEdit_connection, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_linewidth_w1 = QtWidgets.QDoubleSpinBox(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_linewidth_w1.setFont(font)
        self.doubleSpinBox_linewidth_w1.setDecimals(1)
        self.doubleSpinBox_linewidth_w1.setMinimum(0.1)
        self.doubleSpinBox_linewidth_w1.setMaximum(10.0)
        self.doubleSpinBox_linewidth_w1.setSingleStep(0.1)
        self.doubleSpinBox_linewidth_w1.setObjectName("doubleSpinBox_linewidth_w1")
        self.gridLayout.addWidget(self.doubleSpinBox_linewidth_w1, 0, 5, 1, 1)
        self.comboBox_linestyle_w1 = QtWidgets.QComboBox(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_linestyle_w1.setFont(font)
        self.comboBox_linestyle_w1.setObjectName("comboBox_linestyle_w1")
        self.comboBox_linestyle_w1.addItem("")
        self.comboBox_linestyle_w1.addItem("")
        self.comboBox_linestyle_w1.setItemText(1, "")
        self.comboBox_linestyle_w1.addItem("")
        self.comboBox_linestyle_w1.addItem("")
        self.comboBox_linestyle_w1.addItem("")
        self.comboBox_linestyle_w1.addItem("")
        self.gridLayout.addWidget(self.comboBox_linestyle_w1, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.comboBox_marker_w1 = QtWidgets.QComboBox(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_marker_w1.setFont(font)
        self.comboBox_marker_w1.setObjectName("comboBox_marker_w1")
        self.comboBox_marker_w1.addItem("")
        self.comboBox_marker_w1.addItem("")
        self.comboBox_marker_w1.setItemText(1, "")
        self.comboBox_marker_w1.addItem("")
        self.comboBox_marker_w1.addItem("")
        self.comboBox_marker_w1.addItem("")
        self.comboBox_marker_w1.addItem("")
        self.comboBox_marker_w1.addItem("")
        self.comboBox_marker_w1.addItem("")
        self.comboBox_marker_w1.addItem("")
        self.gridLayout.addWidget(self.comboBox_marker_w1, 1, 1, 1, 1)
        self.doubleSpinBox_markersize_w1 = QtWidgets.QDoubleSpinBox(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBox_markersize_w1.setFont(font)
        self.doubleSpinBox_markersize_w1.setDecimals(1)
        self.doubleSpinBox_markersize_w1.setMinimum(0.1)
        self.doubleSpinBox_markersize_w1.setMaximum(20.0)
        self.doubleSpinBox_markersize_w1.setSingleStep(0.1)
        self.doubleSpinBox_markersize_w1.setProperty("value", 5.0)
        self.doubleSpinBox_markersize_w1.setObjectName("doubleSpinBox_markersize_w1")
        self.gridLayout.addWidget(self.doubleSpinBox_markersize_w1, 1, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab_1, "Characteristics")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget_data = QtWidgets.QTableWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_data.sizePolicy().hasHeightForWidth())
        self.tableWidget_data.setSizePolicy(sizePolicy)
        self.tableWidget_data.setBaseSize(QtCore.QSize(0, 0))
        self.tableWidget_data.setObjectName("tableWidget_data")
        self.tableWidget_data.setColumnCount(1)
        self.tableWidget_data.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_data.setHorizontalHeaderItem(0, item)
        self.verticalLayout_3.addWidget(self.tableWidget_data)
        self.tabWidget.addTab(self.tab_2, "Data")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.plainTextEdit_comments = QtWidgets.QPlainTextEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_comments.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_comments.setSizePolicy(sizePolicy)
        self.plainTextEdit_comments.setObjectName("plainTextEdit_comments")
        self.verticalLayout_4.addWidget(self.plainTextEdit_comments)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_save_comment = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_save_comment.setObjectName("pushButton_save_comment")
        self.horizontalLayout_3.addWidget(self.pushButton_save_comment)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab_3, "Comments")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_ylabel_w1 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ylabel_w1.sizePolicy().hasHeightForWidth())
        self.lineEdit_ylabel_w1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_ylabel_w1.setFont(font)
        self.lineEdit_ylabel_w1.setText("")
        self.lineEdit_ylabel_w1.setObjectName("lineEdit_ylabel_w1")
        self.gridLayout_2.addWidget(self.lineEdit_ylabel_w1, 2, 1, 1, 1)
        self.lineEdit_xlabel_w1 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_xlabel_w1.sizePolicy().hasHeightForWidth())
        self.lineEdit_xlabel_w1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_xlabel_w1.setFont(font)
        self.lineEdit_xlabel_w1.setObjectName("lineEdit_xlabel_w1")
        self.gridLayout_2.addWidget(self.lineEdit_xlabel_w1, 1, 1, 1, 1)
        self.lineEdit_title_w1 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_title_w1.sizePolicy().hasHeightForWidth())
        self.lineEdit_title_w1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_title_w1.setFont(font)
        self.lineEdit_title_w1.setObjectName("lineEdit_title_w1")
        self.gridLayout_2.addWidget(self.lineEdit_title_w1, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_2.addWidget(self.label_17)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.checkBox_logx1 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_logx1.setObjectName("checkBox_logx1")
        self.horizontalLayout_2.addWidget(self.checkBox_logx1)
        self.checkBox_logy1 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_logy1.setObjectName("checkBox_logy1")
        self.horizontalLayout_2.addWidget(self.checkBox_logy1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.lineEdit_axis_limits_w1 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_axis_limits_w1.setObjectName("lineEdit_axis_limits_w1")
        self.verticalLayout_5.addWidget(self.lineEdit_axis_limits_w1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.tabWidget.addTab(self.tab_4, "Chart 1")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setContentsMargins(10, 10, 10, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_xlabel_w2 = QtWidgets.QLineEdit(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_xlabel_w2.sizePolicy().hasHeightForWidth())
        self.lineEdit_xlabel_w2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_xlabel_w2.setFont(font)
        self.lineEdit_xlabel_w2.setObjectName("lineEdit_xlabel_w2")
        self.gridLayout_4.addWidget(self.lineEdit_xlabel_w2, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_ylabel_w2 = QtWidgets.QLineEdit(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ylabel_w2.sizePolicy().hasHeightForWidth())
        self.lineEdit_ylabel_w2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_ylabel_w2.setFont(font)
        self.lineEdit_ylabel_w2.setText("")
        self.lineEdit_ylabel_w2.setObjectName("lineEdit_ylabel_w2")
        self.gridLayout_4.addWidget(self.lineEdit_ylabel_w2, 2, 1, 1, 1)
        self.lineEdit_title_w2 = QtWidgets.QLineEdit(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_title_w2.sizePolicy().hasHeightForWidth())
        self.lineEdit_title_w2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_title_w2.setFont(font)
        self.lineEdit_title_w2.setObjectName("lineEdit_title_w2")
        self.gridLayout_4.addWidget(self.lineEdit_title_w2, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.checkBox_logx2 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_logx2.setObjectName("checkBox_logx2")
        self.horizontalLayout.addWidget(self.checkBox_logx2)
        self.checkBox_logy2 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_logy2.setObjectName("checkBox_logy2")
        self.horizontalLayout.addWidget(self.checkBox_logy2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.lineEdit_axis_limits_w2 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_axis_limits_w2.setObjectName("lineEdit_axis_limits_w2")
        self.verticalLayout_6.addWidget(self.lineEdit_axis_limits_w2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 105, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.tabWidget.addTab(self.tab_5, "Chart 2")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_4.addWidget(self.left_Widget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.mpl1_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl1_widget.sizePolicy().hasHeightForWidth())
        self.mpl1_widget.setSizePolicy(sizePolicy)
        self.mpl1_widget.setObjectName("mpl1_widget")
        self.verticalLayout_mpl1 = QtWidgets.QVBoxLayout(self.mpl1_widget)
        self.verticalLayout_mpl1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_mpl1.setObjectName("verticalLayout_mpl1")
        self.horizontalLayout_4.addWidget(self.mpl1_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_ffnen = QtWidgets.QAction(MainWindow)
        self.action_ffnen.setObjectName("action_ffnen")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.label.setBuddy(self.lineEdit_legend)
        self.label_2.setBuddy(self.lineEdit_units)
        self.label_4.setBuddy(self.lineEdit_id)
        self.label_3.setBuddy(self.lineEdit_connection)
        self.label_8.setBuddy(self.doubleSpinBox_linewidth_w1)
        self.label_7.setBuddy(self.comboBox_linestyle_w1)
        self.label_11.setBuddy(self.lineEdit_xlabel_w2)
        self.label_12.setBuddy(self.lineEdit_ylabel_w2)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_legend, self.lineEdit_units)
        MainWindow.setTabOrder(self.lineEdit_units, self.doubleSpinBox_linewidth_w1)
        MainWindow.setTabOrder(self.doubleSpinBox_linewidth_w1, self.doubleSpinBox_markersize_w1)
        MainWindow.setTabOrder(self.doubleSpinBox_markersize_w1, self.lineEdit_title_w1)
        MainWindow.setTabOrder(self.lineEdit_title_w1, self.lineEdit_xlabel_w1)
        MainWindow.setTabOrder(self.lineEdit_xlabel_w1, self.lineEdit_ylabel_w1)
        MainWindow.setTabOrder(self.lineEdit_ylabel_w1, self.lineEdit_title_w2)
        MainWindow.setTabOrder(self.lineEdit_title_w2, self.lineEdit_xlabel_w2)
        MainWindow.setTabOrder(self.lineEdit_xlabel_w2, self.lineEdit_ylabel_w2)
        MainWindow.setTabOrder(self.lineEdit_ylabel_w2, self.comboBox_linestyle_w1)
        MainWindow.setTabOrder(self.comboBox_linestyle_w1, self.treeWidget)
        MainWindow.setTabOrder(self.treeWidget, self.comboBox_marker_w1)
        MainWindow.setTabOrder(self.comboBox_marker_w1, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.lineEdit_connection)
        MainWindow.setTabOrder(self.lineEdit_connection, self.tableWidget_data)
        MainWindow.setTabOrder(self.tableWidget_data, self.lineEdit_id)
        MainWindow.setTabOrder(self.lineEdit_id, self.plainTextEdit_comments)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Row"))
        self.label_2.setText(_translate("MainWindow", "Units"))
        self.label_4.setText(_translate("MainWindow", "ID"))
        self.label_3.setText(_translate("MainWindow", "Connection"))
        self.comboBox_linestyle_w1.setItemText(0, _translate("MainWindow", "-"))
        self.comboBox_linestyle_w1.setItemText(2, _translate("MainWindow", "--"))
        self.comboBox_linestyle_w1.setItemText(3, _translate("MainWindow", "-."))
        self.comboBox_linestyle_w1.setItemText(4, _translate("MainWindow", ":"))
        self.comboBox_linestyle_w1.setItemText(5, _translate("MainWindow", "steps"))
        self.label_8.setText(_translate("MainWindow", "Linewidth"))
        self.label_7.setText(_translate("MainWindow", "Linestyle"))
        self.label_9.setText(_translate("MainWindow", "Marker"))
        self.comboBox_marker_w1.setItemText(0, _translate("MainWindow", "o"))
        self.comboBox_marker_w1.setItemText(2, _translate("MainWindow", "+"))
        self.comboBox_marker_w1.setItemText(3, _translate("MainWindow", ","))
        self.comboBox_marker_w1.setItemText(4, _translate("MainWindow", "."))
        self.comboBox_marker_w1.setItemText(5, _translate("MainWindow", "1"))
        self.comboBox_marker_w1.setItemText(6, _translate("MainWindow", "2"))
        self.comboBox_marker_w1.setItemText(7, _translate("MainWindow", "3"))
        self.comboBox_marker_w1.setItemText(8, _translate("MainWindow", "4"))
        self.label_10.setText(_translate("MainWindow", "Markersize"))
        item = self.tableWidget_data.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ein Text"))
        self.pushButton_save_comment.setText(_translate("MainWindow", "Save"))
        self.label_6.setText(_translate("MainWindow", "y-Axis Label"))
        self.label_5.setText(_translate("MainWindow", "x-Axis Label"))
        self.label_13.setText(_translate("MainWindow", "Title"))
        self.label_17.setText(_translate("MainWindow", "Limits (x_min; x_max; y_min; y_max)"))
        self.checkBox_logx1.setText(_translate("MainWindow", "Log X"))
        self.checkBox_logy1.setText(_translate("MainWindow", "Log Y"))
        self.label_11.setText(_translate("MainWindow", "x-Axis Label"))
        self.label_12.setText(_translate("MainWindow", "y-Axis Label"))
        self.label_14.setText(_translate("MainWindow", "Title"))
        self.label_16.setText(_translate("MainWindow", "Limits (x_min; x_max; y_min; y_max)"))
        self.checkBox_logx2.setText(_translate("MainWindow", "Log X"))
        self.checkBox_logy2.setText(_translate("MainWindow", "Log Y"))
        self.lineEdit_axis_limits_w2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Type &quot;auto&quot; or &quot;a&quot; if yout want to leave </p></body></html>"))
        self.action_ffnen.setText(_translate("MainWindow", "Öffnen"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionExport.setText(_translate("MainWindow", "Export"))

